{:config {:name :end-game, :description "End Game", :order 0}
 :data
 [
  [:node-create [] :map]
  [:node-create [:login] :map]
  [:node-create [:login :name] :map]
  [:transform-enable [:login :name] :login [{:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:login :name], :io.pedestal.app.messages.param/value {}} {:io.pedestal.app.messages/type :set-focus, :io.pedestal.app.messages/topic :io.pedestal.app.messages/app-model, :name :wait}]]
  :break
  [:value [:login :name] nil "Feanor"]
  :break
  [:value [:login :name] "Feanor" nil]
  [:transform-disable [:login :name] :login [{:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:login :name], :io.pedestal.app.messages.param/value {}} {:io.pedestal.app.messages/type :set-focus, :io.pedestal.app.messages/topic :io.pedestal.app.messages/app-model, :name :wait}]]
  [:node-destroy [:login :name] :map]
  [:node-destroy [:login] :map]
  [:node-create [:wait] :map]
  [:node-create [:wait :start] :map]
  [:transform-enable [:wait :start] :start-game [{:io.pedestal.app.messages/topic :io.pedestal.app.messages/output, :payload {:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:active-game], :value true}} {:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:active-game], :value true}]]
  [:node-create [:wait :counters] :map]
  [:node-create [:wait :counters "Feanor"] :map]
  :break
  [:node-create [:wait :counters "abc"] :map]
  [:value [:wait :counters "abc"] nil 0]
  :break
  [:node-create [:wait :counters "xyz"] :map]
  [:value [:wait :counters "xyz"] nil 0]
  :break
  [:value [:wait :counters "abc"] 0 1]
  :break
  [:value [:wait :counters "xyz"] 0 1]
  :break
  [:value [:wait :counters "abc"] 1 nil]
  [:node-destroy [:wait :counters "abc"] :map]
  [:value [:wait :counters "xyz"] 1 nil]
  [:node-destroy [:wait :counters "xyz"] :map]
  [:node-destroy [:wait :counters "Feanor"] :map]
  [:node-destroy [:wait :counters] :map]
  [:transform-disable [:wait :start] :start-game [{:io.pedestal.app.messages/topic :io.pedestal.app.messages/output, :payload {:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:active-game], :value true}} {:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:active-game], :value true}]]
  [:node-destroy [:wait :start] :map]
  [:node-destroy [:wait] :map]
  [:node-create [:main] :map]
  [:node-create [:main :my-counter] :map]
  [:transform-enable [:main :my-counter] :add-points [{:io.pedestal.app.messages/topic [:my-counter], :io.pedestal.app.messages.param/points {}}]]
  [:node-create [:main :average-count] :map]
  [:value [:main :average-count] nil 1]
  [:node-create [:main :max-count] :map]
  [:value [:main :max-count] nil 1]
  [:node-create [:main :total-count] :map]
  [:value [:main :total-count] nil 2]
  [:node-create [:main :counters] :map]
  [:node-create [:main :counters "Feanor"] :map]
  [:node-create [:main :counters "xyz"] :map]
  [:value [:main :counters "xyz"] nil 1]
  [:node-create [:main :counters "abc"] :map]
  [:value [:main :counters "abc"] nil 1]
  [:node-create [:pedestal] :map]
  [:node-create [:pedestal :debug] :map]
  [:node-create [:pedestal :debug :dataflow-time-avg] :map]
  [:value [:pedestal :debug :dataflow-time-avg] nil 21]
  [:node-create [:pedestal :debug :dataflow-time-max] :map]
  [:value [:pedestal :debug :dataflow-time-max] nil 41]
  [:node-create [:pedestal :debug :dataflow-time] :map]
  [:value [:pedestal :debug :dataflow-time] nil 32]
  [:node-create [:main :player-order] :map]
  [:node-create [:main :player-order "abc"] :map]
  [:value [:main :player-order "abc"] nil 1]
  [:node-create [:main :player-order "xyz"] :map]
  [:value [:main :player-order "xyz"] nil 0]
  [:node-create [:main :player-order "Feanor"] :map]
  [:value [:main :player-order "Feanor"] nil 2]
  [:node-create [:main :remove-bubbles] :map]
  [:value [:main :remove-bubbles] nil {:total 2}]
  [:node-create [:main :add-bubbles] :map]
  [:value [:main :add-bubbles] nil {:clock 11, :count 3}]
  :break
  [:value [:main :add-bubbles] {:clock 11, :count 3} {:clock 12, :count 3}]
  [:value [:pedestal :debug :dataflow-time-avg] 21 20]
  [:value [:pedestal :debug :dataflow-time] 32 8]
  :break
  [:value [:main :max-count] 1 2]
  [:value [:main :total-count] 2 3]
  [:value [:main :counters "abc"] 1 2]
  [:value [:main :player-order "abc"] 1 0]
  [:value [:main :player-order "xyz"] 0 1]
  [:value [:main :remove-bubbles] {:total 2} {:total 3}]
  [:value [:pedestal :debug :dataflow-time] 8 28]
  :break
  [:value [:main :add-bubbles] {:clock 12, :count 3} {:clock 13, :count 3}]
  [:value [:pedestal :debug :dataflow-time] 28 9]
  :break
  [:value [:main :average-count] 1 1.33]
  [:value [:main :max-count] 2 3]
  [:value [:main :total-count] 3 4]
  [:value [:main :counters "abc"] 2 3]
  [:value [:main :remove-bubbles] {:total 3} {:total 4}]
  [:value [:pedestal :debug :dataflow-time] 9 25]
  :break
  [:value [:main :add-bubbles] {:clock 13, :count 3} {:clock 14, :count 3}]
  [:value [:pedestal :debug :dataflow-time-avg] 20 19]
  [:value [:pedestal :debug :dataflow-time] 25 8]
  :break
  [:value [:main :average-count] 1.33 34.67]
  [:value [:main :max-count] 3 100]
  [:value [:main :total-count] 4 104]
  [:value [:main :counters "Feanor"] nil 100]
  [:value [:main :player-order "abc"] 0 1]
  [:value [:main :player-order "xyz"] 1 2]
  [:value [:main :player-order "Feanor"] 2 0]
  [:value [:pedestal :debug :dataflow-time-avg] 19 20]
  [:value [:pedestal :debug :dataflow-time] 8 27]
  :break
  [:value [:main :average-count] 34.67 35]
  [:value [:main :total-count] 104 105]
  [:value [:main :counters "xyz"] 1 2]
  [:value [:main :remove-bubbles] {:total 4} {:total 5}]
  [:value [:pedestal :debug :dataflow-time] 27 23]
  :break
  [:value [:main :average-count] 35 35.33]
  [:value [:main :total-count] 105 106]
  [:value [:main :counters "abc"] 3 4]
  [:value [:main :remove-bubbles] {:total 5} {:total 6}]
  [:value [:pedestal :debug :dataflow-time-avg] 20 21]
  [:value [:pedestal :debug :dataflow-time-max] 41 48]
  [:value [:pedestal :debug :dataflow-time] 23 48]
  :break
  [:value [:main :add-bubbles] {:clock 14, :count 3} {:clock 15, :count 3}]
  [:value [:pedestal :debug :dataflow-time-avg] 21 20]
  [:value [:pedestal :debug :dataflow-time] 48 7]
  :break
  [:value [:main :average-count] 35.33 35.67]
  [:value [:main :total-count] 106 107]
  [:value [:main :counters "abc"] 4 5]
  [:value [:main :remove-bubbles] {:total 6} {:total 7}]
  [:value [:pedestal :debug :dataflow-time-avg] 20 21]
  [:value [:pedestal :debug :dataflow-time] 7 27]
  :break
  [:value [:main :add-bubbles] {:clock 15, :count 3} {:clock 16, :count 3}]
  [:value [:pedestal :debug :dataflow-time-avg] 21 20]
  [:value [:pedestal :debug :dataflow-time] 27 7]
  :break
  [:value [:main :average-count] 35.67 69]
  [:value [:main :max-count] 100 200]
  [:value [:main :total-count] 107 207]
  [:value [:main :counters "Feanor"] 100 200]
  [:value [:pedestal :debug :dataflow-time] 7 18]
  :break
  [:value [:main :average-count] 69 69.33]
  [:value [:main :total-count] 207 208]
  [:value [:main :counters "xyz"] 2 3]
  [:value [:main :remove-bubbles] {:total 7} {:total 8}]
  [:value [:pedestal :debug :dataflow-time] 18 22]
  :break
  [:value [:main :average-count] 69.33 69.67]
  [:value [:main :total-count] 208 209]
  [:value [:main :counters "abc"] 5 6]
  [:value [:main :remove-bubbles] {:total 8} {:total 9}]
  [:value [:pedestal :debug :dataflow-time] 22 24]
  :break
  [:value [:main :add-bubbles] {:clock 16, :count 3} {:clock 17, :count 3}]
  [:value [:pedestal :debug :dataflow-time] 24 7]
  :break
  [:value [:main :average-count] 69.67 70]
  [:value [:main :total-count] 209 210]
  [:value [:main :counters "abc"] 6 7]
  [:value [:main :remove-bubbles] {:total 9} {:total 10}]
  [:value [:pedestal :debug :dataflow-time] 7 27]
  :break
  [:value [:main :add-bubbles] {:clock 17, :count 3} {:clock 18, :count 3}]
  [:value [:pedestal :debug :dataflow-time] 27 8]
  :break
  [:value [:main :average-count] 70 70.33]
  [:value [:main :total-count] 210 211]
  [:value [:main :counters "abc"] 7 8]
  [:value [:main :remove-bubbles] {:total 10} {:total 11}]
  [:value [:pedestal :debug :dataflow-time] 8 23]
  :break
  [:value [:main :add-bubbles] {:clock 18, :count 3} {:clock 19, :count 3}]
  [:value [:pedestal :debug :dataflow-time-avg] 20 19]
  [:value [:pedestal :debug :dataflow-time] 23 7]
  :break
  [:value [:main :average-count] 70.33 103.67]
  [:value [:main :max-count] 200 300]
  [:value [:main :total-count] 211 311]
  [:value [:main :counters "Feanor"] 200 300]
  [:value [:pedestal :debug :dataflow-time-avg] 19 20]
  [:value [:pedestal :debug :dataflow-time-max] 48 60]
  [:value [:pedestal :debug :dataflow-time] 7 60]
  :break
  [:value [:main :average-count] 103.67 3.67]
  [:value [:main :total-count] 311 11]
  [:value [:main :counters "Feanor"] 300 0]
  [:value [:main :player-order "abc"] 1 0]
  [:value [:main :player-order "xyz"] 2 1]
  [:value [:main :player-order "Feanor"] 0 2]
  [:value [:pedestal :debug :dataflow-time-avg] 20 21]
  [:value [:pedestal :debug :dataflow-time] 60 26]
  :break
  [:value [:main :max-count] 300 0]
  [:value [:pedestal :debug :dataflow-time-avg] 21 20]
  [:value [:pedestal :debug :dataflow-time] 26 7]
  :break
  [:value [:main :average-count] 3.67 1.5]
  [:value [:main :max-count] 0 3]
  [:value [:main :total-count] 11 3]
  [:value [:main :counters "abc"] 8 0]
  [:value [:main :player-order "abc"] 0 2]
  [:value [:main :player-order "xyz"] 1 0]
  [:value [:main :player-order "Feanor"] 2 1]
  [:value [:main :remove-bubbles] {:total 11} {:total 3}]
  [:value [:pedestal :debug :dataflow-time] 7 31]
  :break
  [:value [:pedestal :debug :dataflow-time] 31 5]
  :break
  [:value [:main :average-count] 1.5 0]
  [:value [:main :total-count] 3 0]
  [:value [:main :counters "xyz"] 3 0]
  [:value [:main :remove-bubbles] {:total 3} {:total 0}]
  [:value [:pedestal :debug :dataflow-time] 5 21]
  :break
  [:value [:main :counters "abc"] 0 nil]
  [:node-destroy [:main :counters "abc"] :map]
  [:value [:main :counters "xyz"] 0 nil]
  [:node-destroy [:main :counters "xyz"] :map]
  [:value [:main :counters "Feanor"] 0 nil]
  [:node-destroy [:main :counters "Feanor"] :map]
  [:node-destroy [:main :counters] :map]
  [:transform-disable [:main :my-counter] :add-points [{:io.pedestal.app.messages/topic [:my-counter], :io.pedestal.app.messages.param/points {}}]]
  [:node-destroy [:main :my-counter] :map]
  [:value [:main :remove-bubbles] {:total 0} nil]
  [:node-destroy [:main :remove-bubbles] :map]
  [:value [:main :player-order "abc"] 2 nil]
  [:node-destroy [:main :player-order "abc"] :map]
  [:value [:main :player-order "xyz"] 0 nil]
  [:node-destroy [:main :player-order "xyz"] :map]
  [:value [:main :player-order "Feanor"] 1 nil]
  [:node-destroy [:main :player-order "Feanor"] :map]
  [:node-destroy [:main :player-order] :map]
  [:value [:main :add-bubbles] {:clock 19, :count 3} nil]
  [:node-destroy [:main :add-bubbles] :map]
  [:value [:main :average-count] 0 nil]
  [:node-destroy [:main :average-count] :map]
  [:value [:main :max-count] 3 nil]
  [:node-destroy [:main :max-count] :map]
  [:value [:main :total-count] 0 nil]
  [:node-destroy [:main :total-count] :map]
  [:node-destroy [:main] :map]
  [:value [:pedestal :debug :dataflow-time-max] 60 nil]
  [:node-destroy [:pedestal :debug :dataflow-time-max] :map]
  [:value [:pedestal :debug :dataflow-time] 21 nil]
  [:node-destroy [:pedestal :debug :dataflow-time] :map]
  [:value [:pedestal :debug :dataflow-time-avg] 20 nil]
  [:node-destroy [:pedestal :debug :dataflow-time-avg] :map]
  [:node-destroy [:pedestal :debug] :map]
  [:node-destroy [:pedestal] :map]
  [:node-create [:wait] :map]
  [:node-create [:wait :start] :map]
  [:transform-enable [:wait :start] :start-game [{:io.pedestal.app.messages/topic :io.pedestal.app.messages/output, :payload {:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:active-game], :value true}} {:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:active-game], :value true}]]
  [:node-create [:wait :counters] :map]
  [:node-create [:wait :counters "Feanor"] :map]
  [:value [:wait :counters "Feanor"] nil 0]
  [:node-create [:wait :counters "xyz"] :map]
  [:value [:wait :counters "xyz"] nil 0]
  [:node-create [:wait :counters "abc"] :map]
  [:value [:wait :counters "abc"] nil 0]
  [:node-create [:wait :winner] :map]
  [:value [:wait :winner] nil {:player "Feanor", :score 300}]
  [:node-create [:wait :high-scores] :map]
  [:value [:wait :high-scores] nil ({:player "Feanor", :score 300})]
  :break
  [:value [:wait :counters "xyz"] 0 4]
  :break
  [:value [:wait :counters "abc"] 0 9]
  :break
  [:value [:wait :counters "abc"] 9 10]
  :break
  [:value [:wait :counters "xyz"] 4 5]
  :break
  [:value [:wait :counters "abc"] 10 nil]
  [:node-destroy [:wait :counters "abc"] :map]
  [:value [:wait :counters "xyz"] 5 nil]
  [:node-destroy [:wait :counters "xyz"] :map]
  [:value [:wait :counters "Feanor"] 0 nil]
  [:node-destroy [:wait :counters "Feanor"] :map]
  [:node-destroy [:wait :counters] :map]
  [:value [:wait :high-scores] ({:player "Feanor", :score 300}) nil]
  [:node-destroy [:wait :high-scores] :map]
  [:value [:wait :winner] {:player "Feanor", :score 300} nil]
  [:node-destroy [:wait :winner] :map]
  [:transform-disable [:wait :start] :start-game [{:io.pedestal.app.messages/topic :io.pedestal.app.messages/output, :payload {:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:active-game], :value true}} {:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:active-game], :value true}]]
  [:node-destroy [:wait :start] :map]
  [:node-destroy [:wait] :map]
  [:node-create [:main] :map]
  [:node-create [:main :my-counter] :map]
  [:transform-enable [:main :my-counter] :add-points [{:io.pedestal.app.messages/topic [:my-counter], :io.pedestal.app.messages.param/points {}}]]
  [:node-create [:main :average-count] :map]
  [:value [:main :average-count] nil 5]
  [:node-create [:main :max-count] :map]
  [:value [:main :max-count] nil 10]
  [:node-create [:main :total-count] :map]
  [:value [:main :total-count] nil 15]
  [:node-create [:main :counters] :map]
  [:node-create [:main :counters "Feanor"] :map]
  [:value [:main :counters "Feanor"] nil 0]
  [:node-create [:main :counters "xyz"] :map]
  [:value [:main :counters "xyz"] nil 5]
  [:node-create [:main :counters "abc"] :map]
  [:value [:main :counters "abc"] nil 10]
  [:node-create [:pedestal] :map]
  [:node-create [:pedestal :debug] :map]
  [:node-create [:pedestal :debug :dataflow-time-avg] :map]
  [:value [:pedestal :debug :dataflow-time-avg] nil 20]
  [:node-create [:pedestal :debug :dataflow-time-max] :map]
  [:value [:pedestal :debug :dataflow-time-max] nil 60]
  [:node-create [:pedestal :debug :dataflow-time] :map]
  [:value [:pedestal :debug :dataflow-time] nil 22]
  [:node-create [:main :player-order] :map]
  [:node-create [:main :player-order "abc"] :map]
  [:value [:main :player-order "abc"] nil 0]
  [:node-create [:main :player-order "xyz"] :map]
  [:value [:main :player-order "xyz"] nil 1]
  [:node-create [:main :player-order "Feanor"] :map]
  [:value [:main :player-order "Feanor"] nil 2]
  [:node-create [:main :remove-bubbles] :map]
  [:value [:main :remove-bubbles] nil {:total 15}]
  [:node-create [:main :add-bubbles] :map]
  [:value [:main :add-bubbles] nil {:clock 20, :count 3}]
  :break
  [:value [:main :average-count] 5 5.33]
  [:value [:main :max-count] 10 11]
  [:value [:main :total-count] 15 16]
  [:value [:main :counters "abc"] 10 11]
  [:value [:main :remove-bubbles] {:total 15} {:total 16}]
  [:value [:pedestal :debug :dataflow-time] 22 24]
  :break
  [:value [:main :add-bubbles] {:clock 20, :count 3} {:clock 21, :count 3}]
  [:value [:pedestal :debug :dataflow-time] 24 7]
  :break
  [:value [:main :average-count] 5.33 5.67]
  [:value [:main :max-count] 11 12]
  [:value [:main :total-count] 16 17]
  [:value [:main :counters "abc"] 11 12]
  [:value [:main :remove-bubbles] {:total 16} {:total 17}]
  [:value [:pedestal :debug :dataflow-time] 7 22]
  :break
  [:value [:main :average-count] 5.67 6]
  [:value [:main :total-count] 17 18]
  [:value [:main :counters "xyz"] 5 6]
  [:value [:main :remove-bubbles] {:total 17} {:total 18}]
  [:value [:pedestal :debug :dataflow-time] 22 21]
  :break
  [:value [:main :average-count] 6 6.33]
  [:value [:main :max-count] 12 13]
  [:value [:main :total-count] 18 19]
  [:value [:main :counters "abc"] 12 13]
  [:value [:main :remove-bubbles] {:total 18} {:total 19}]
  :break
  [:value [:main :add-bubbles] {:clock 21, :count 3} {:clock 22, :count 3}]
  [:value [:pedestal :debug :dataflow-time] 21 10]
  :break
  [:value [:main :average-count] 6.33 6.67]
  [:value [:main :max-count] 13 14]
  [:value [:main :total-count] 19 20]
  [:value [:main :counters "abc"] 13 14]
  [:value [:main :remove-bubbles] {:total 19} {:total 20}]
  [:value [:pedestal :debug :dataflow-time] 10 23]
  :break
  [:value [:main :average-count] 6.67 7]
  [:value [:main :max-count] 14 15]
  [:value [:main :total-count] 20 21]
  [:value [:main :counters "abc"] 14 15]
  [:value [:main :remove-bubbles] {:total 20} {:total 21}]
  [:value [:pedestal :debug :dataflow-time] 23 21]
  :break
  [:value [:main :add-bubbles] {:clock 22, :count 3} {:clock 23, :count 3}]
  [:value [:pedestal :debug :dataflow-time] 21 8]
  :break
  [:value [:main :average-count] 7 7.33]
  [:value [:main :total-count] 21 22]
  [:value [:main :counters "xyz"] 6 7]
  [:value [:main :remove-bubbles] {:total 21} {:total 22}]
  [:value [:pedestal :debug :dataflow-time] 8 22]
  :break
  [:value [:main :average-count] 7.33 174]
  [:value [:main :max-count] 15 500]
  [:value [:main :total-count] 22 522]
  [:value [:main :counters "Feanor"] 0 500]
  [:value [:main :player-order "abc"] 0 1]
  [:value [:main :player-order "xyz"] 1 2]
  [:value [:main :player-order "Feanor"] 2 0]
  [:value [:pedestal :debug :dataflow-time-avg] 20 21]
  [:value [:pedestal :debug :dataflow-time-max] 60 72]
  [:value [:pedestal :debug :dataflow-time] 22 72]
  :break
  [:value [:main :average-count] 174 7.33]
  [:value [:main :total-count] 522 22]
  [:value [:main :counters "Feanor"] 500 0]
  [:value [:main :player-order "abc"] 1 0]
  [:value [:main :player-order "xyz"] 2 1]
  [:value [:main :player-order "Feanor"] 0 2]
  [:value [:pedestal :debug :dataflow-time] 72 26]
  :break
  [:value [:main :max-count] 500 0]
  [:value [:pedestal :debug :dataflow-time] 26 5]
  :break
  [:value [:main :average-count] 7.33 3.5]
  [:value [:main :max-count] 0 7]
  [:value [:main :total-count] 22 7]
  [:value [:main :counters "abc"] 15 0]
  [:value [:main :player-order "abc"] 0 2]
  [:value [:main :player-order "xyz"] 1 0]
  [:value [:main :player-order "Feanor"] 2 1]
  [:value [:main :remove-bubbles] {:total 22} {:total 7}]
  [:value [:pedestal :debug :dataflow-time] 5 32]
  :break
  [:value [:pedestal :debug :dataflow-time-avg] 21 20]
  [:value [:pedestal :debug :dataflow-time] 32 2]
  :break
  [:value [:main :average-count] 3.5 0]
  [:value [:main :total-count] 7 0]
  [:value [:main :counters "xyz"] 7 0]
  [:value [:main :remove-bubbles] {:total 7} {:total 0}]
  [:value [:pedestal :debug :dataflow-time] 2 22]
  :break
  [:value [:main :counters "abc"] 0 nil]
  [:node-destroy [:main :counters "abc"] :map]
  [:value [:main :counters "xyz"] 0 nil]
  [:node-destroy [:main :counters "xyz"] :map]
  [:value [:main :counters "Feanor"] 0 nil]
  [:node-destroy [:main :counters "Feanor"] :map]
  [:node-destroy [:main :counters] :map]
  [:transform-disable [:main :my-counter] :add-points [{:io.pedestal.app.messages/topic [:my-counter], :io.pedestal.app.messages.param/points {}}]]
  [:node-destroy [:main :my-counter] :map]
  [:value [:main :remove-bubbles] {:total 0} nil]
  [:node-destroy [:main :remove-bubbles] :map]
  [:value [:main :player-order "abc"] 2 nil]
  [:node-destroy [:main :player-order "abc"] :map]
  [:value [:main :player-order "xyz"] 0 nil]
  [:node-destroy [:main :player-order "xyz"] :map]
  [:value [:main :player-order "Feanor"] 1 nil]
  [:node-destroy [:main :player-order "Feanor"] :map]
  [:node-destroy [:main :player-order] :map]
  [:value [:main :add-bubbles] {:clock 23, :count 3} nil]
  [:node-destroy [:main :add-bubbles] :map]
  [:value [:main :average-count] 0 nil]
  [:node-destroy [:main :average-count] :map]
  [:value [:main :max-count] 7 nil]
  [:node-destroy [:main :max-count] :map]
  [:value [:main :total-count] 0 nil]
  [:node-destroy [:main :total-count] :map]
  [:node-destroy [:main] :map]
  [:value [:pedestal :debug :dataflow-time-avg] 20 nil]
  [:node-destroy [:pedestal :debug :dataflow-time-avg] :map]
  [:value [:pedestal :debug :dataflow-time-max] 72 nil]
  [:node-destroy [:pedestal :debug :dataflow-time-max] :map]
  [:value [:pedestal :debug :dataflow-time] 22 nil]
  [:node-destroy [:pedestal :debug :dataflow-time] :map]
  [:node-destroy [:pedestal :debug] :map]
  [:node-destroy [:pedestal] :map]
  [:node-create [:wait] :map]
  [:node-create [:wait :start] :map]
  [:transform-enable [:wait :start] :start-game [{:io.pedestal.app.messages/topic :io.pedestal.app.messages/output, :payload {:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:active-game], :value true}} {:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:active-game], :value true}]]
  [:node-create [:wait :counters] :map]
  [:node-create [:wait :counters "Feanor"] :map]
  [:value [:wait :counters "Feanor"] nil 0]
  [:node-create [:wait :counters "xyz"] :map]
  [:value [:wait :counters "xyz"] nil 0]
  [:node-create [:wait :counters "abc"] :map]
  [:value [:wait :counters "abc"] nil 0]
  [:node-create [:wait :winner] :map]
  [:value [:wait :winner] nil {:player "Feanor", :score 500}]
  [:node-create [:wait :high-scores] :map]
  [:value [:wait :high-scores] nil ({:player "Feanor", :score 500} {:player "Feanor", :score 300})]
  :break
  [:value [:wait :counters "abc"] 0 16]
  :break
  [:value [:wait :counters "abc"] 16 17]
  :break
  [:value [:wait :counters "xyz"] 0 8]
 ]}