{:config {:name :login, :description "Login", :order 0}
 :data
 [
  [:node-create [] :map]
  [:node-create [:login] :map]
  [:node-create [:login :name] :map]
  [:transform-enable [:login :name] :login [{:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:login :name], :io.pedestal.app.messages.param/value {}} {:io.pedestal.app.messages/type :set-focus, :io.pedestal.app.messages/topic :io.pedestal.app.messages/app-model, :name :game}]]
  :break
  [:value [:login :name] nil "Feanor"]
  :break
  [:value [:login :name] "Feanor" nil]
  [:transform-disable [:login :name] :login [{:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:login :name], :io.pedestal.app.messages.param/value {}} {:io.pedestal.app.messages/type :set-focus, :io.pedestal.app.messages/topic :io.pedestal.app.messages/app-model, :name :game}]]
  [:node-destroy [:login :name] :map]
  [:node-destroy [:login] :map]
  [:node-create [:main] :map]
  [:node-create [:main :my-counter] :map]
  [:transform-enable [:main :my-counter] :add-points [{:io.pedestal.app.messages/topic [:my-counter], :io.pedestal.app.messages.param/points {}}]]
  [:node-create [:main :average-count] :map]
  [:value [:main :average-count] nil 3.33]
  [:node-create [:main :max-count] :map]
  [:value [:main :max-count] nil 7]
  [:node-create [:main :total-count] :map]
  [:value [:main :total-count] nil 10]
  [:node-create [:main :counters] :map]
  [:node-create [:main :counters "Feanor"] :map]
  [:node-create [:main :counters "xyz"] :map]
  [:value [:main :counters "xyz"] nil 3]
  [:node-create [:main :counters "abc"] :map]
  [:value [:main :counters "abc"] nil 7]
  [:node-create [:pedestal] :map]
  [:node-create [:pedestal :debug] :map]
  [:node-create [:pedestal :debug :dataflow-time-avg] :map]
  [:value [:pedestal :debug :dataflow-time-avg] nil 16]
  [:node-create [:pedestal :debug :dataflow-time-max] :map]
  [:value [:pedestal :debug :dataflow-time-max] nil 33]
  [:node-create [:pedestal :debug :dataflow-time] :map]
  [:value [:pedestal :debug :dataflow-time] nil 19]
  [:node-create [:main :player-order] :map]
  [:node-create [:main :player-order "abc"] :map]
  [:value [:main :player-order "abc"] nil 0]
  [:node-create [:main :player-order "xyz"] :map]
  [:value [:main :player-order "xyz"] nil 1]
  [:node-create [:main :player-order "Feanor"] :map]
  [:value [:main :player-order "Feanor"] nil 2]
  [:node-create [:main :add-bubbles] :map]
  [:value [:main :add-bubbles] nil {:clock 7, :count 3}]
  :break
  [:value [:main :add-bubbles] {:clock 7, :count 3} {:clock 8, :count 3}]
  [:value [:pedestal :debug :dataflow-time] 19 10]
  :break
  [:value [:main :average-count] 3.33 3.67]
  [:value [:main :max-count] 7 8]
  [:value [:main :total-count] 10 11]
  [:value [:main :counters "abc"] 7 8]
  [:value [:pedestal :debug :dataflow-time-avg] 16 17]
  [:value [:pedestal :debug :dataflow-time-max] 33 37]
  [:value [:pedestal :debug :dataflow-time] 10 37]
  :break
  [:value [:main :average-count] 3.67 4]
  [:value [:main :total-count] 11 12]
  [:value [:main :counters "xyz"] 3 4]
  [:value [:pedestal :debug :dataflow-time] 37 15]
  :break
  [:value [:main :add-bubbles] {:clock 8, :count 3} {:clock 9, :count 3}]
  [:value [:pedestal :debug :dataflow-time-avg] 17 16]
  [:value [:pedestal :debug :dataflow-time] 15 5]
  :break
  [:value [:main :average-count] 4 4.33]
  [:value [:main :max-count] 8 9]
  [:value [:main :total-count] 12 13]
  [:value [:main :counters "abc"] 8 9]
  [:value [:pedestal :debug :dataflow-time] 5 18]
  :break
  [:value [:main :add-bubbles] {:clock 9, :count 3} {:clock 10, :count 3}]
  [:value [:pedestal :debug :dataflow-time] 18 6]
  :break
  [:value [:main :average-count] 4.33 4.67]
  [:value [:main :max-count] 9 10]
  [:value [:main :total-count] 13 14]
  [:value [:main :counters "abc"] 9 10]
  [:value [:pedestal :debug :dataflow-time] 6 17]
  :break
  [:value [:main :average-count] 4.67 11.33]
  [:value [:main :max-count] 10 20]
  [:value [:main :total-count] 14 34]
  [:value [:main :counters "Feanor"] nil 20]
  [:value [:main :player-order "abc"] 0 1]
  [:value [:main :player-order "xyz"] 1 2]
  [:value [:main :player-order "Feanor"] 2 0]
  [:value [:pedestal :debug :dataflow-time] 17 22]
  :break
  [:value [:main :average-count] 11.33 11.67]
  [:value [:main :total-count] 34 35]
  [:value [:main :counters "xyz"] 4 5]
  [:value [:pedestal :debug :dataflow-time] 22 14]
  :break
  [:value [:main :add-bubbles] {:clock 10, :count 3} {:clock 11, :count 3}]
  [:value [:pedestal :debug :dataflow-time-avg] 16 15]
  [:value [:pedestal :debug :dataflow-time] 14 6]
  :break
  [:value [:main :average-count] 11.67 12]
  [:value [:main :total-count] 35 36]
  [:value [:main :counters "abc"] 10 11]
  [:value [:pedestal :debug :dataflow-time] 6 14]
 ]}