{:config {:name :tutorial, :description "Tutorial Recording", :order 0}
 :data
 [
  [:node-create [] :map]
  [:node-create [:tutorial] :map]
  [:node-create [:pedestal] :map]
  [:node-create [:pedestal :debug] :map]
  [:node-create [:pedestal :debug :dataflow-time-avg] :map]
  [:value [:pedestal :debug :dataflow-time-avg] nil 21]
  [:node-create [:pedestal :debug :dataflow-time-max] :map]
  [:value [:pedestal :debug :dataflow-time-max] nil 31]
  [:node-create [:pedestal :debug :dataflow-time] :map]
  [:value [:pedestal :debug :dataflow-time] nil 11]
  [:node-create [:tutorial :my-counter] :map]
  [:value [:tutorial :my-counter] nil 1]
  [:transform-enable [:tutorial :my-counter] :inc [{:io.pedestal.app.messages/topic [:my-counter]}]]
  [:node-create [:tutorial :other-counters] :map]
  [:node-create [:tutorial :other-counters "abc"] :map]
  [:value [:tutorial :other-counters "abc"] nil 1]
  [:node-create [:tutorial :other-counters "xyz"] :map]
  [:value [:tutorial :other-counters "xyz"] nil 1]
  [:node-create [:tutorial :total-count] :map]
  [:value [:tutorial :total-count] nil 3]
  [:node-create [:tutorial :average-count] :map]
  [:value [:tutorial :average-count] nil 1]
  [:node-create [:tutorial :max-count] :map]
  [:value [:tutorial :max-count] nil 1]
  :break
  [:value [:tutorial :other-counters "abc"] 1 2]
  [:value [:tutorial :average-count] 1 1.33]
  [:value [:tutorial :max-count] 1 2]
  [:value [:tutorial :total-count] 3 4]
  [:value [:pedestal :debug :dataflow-time-avg] 21 23]
  [:value [:pedestal :debug :dataflow-time] 11 28]
  :break
  [:value [:tutorial :other-counters "abc"] 2 3]
  [:value [:tutorial :average-count] 1.33 1.67]
  [:value [:tutorial :max-count] 2 3]
  [:value [:tutorial :total-count] 4 5]
  [:value [:pedestal :debug :dataflow-time-avg] 23 20]
  [:value [:pedestal :debug :dataflow-time] 28 13]
  :break
  [:value [:tutorial :other-counters "xyz"] 1 2]
  [:value [:tutorial :average-count] 1.67 2]
  [:value [:tutorial :total-count] 5 6]
  [:value [:pedestal :debug :dataflow-time-avg] 20 18]
  [:value [:pedestal :debug :dataflow-time] 13 10]
  :break
  [:value [:tutorial :other-counters "abc"] 3 4]
  [:value [:tutorial :average-count] 2 2.33]
  [:value [:tutorial :max-count] 3 4]
  [:value [:tutorial :total-count] 6 7]
  [:value [:pedestal :debug :dataflow-time-avg] 18 17]
  [:value [:pedestal :debug :dataflow-time] 10 13]
  :break
  [:value [:tutorial :other-counters "abc"] 4 5]
  [:value [:tutorial :average-count] 2.33 2.67]
  [:value [:tutorial :max-count] 4 5]
  [:value [:tutorial :total-count] 7 8]
  [:value [:pedestal :debug :dataflow-time] 13 18]
  :break
  [:value [:tutorial :my-counter] 1 2]
  [:value [:tutorial :average-count] 2.67 3]
  [:value [:tutorial :total-count] 8 9]
  [:value [:pedestal :debug :dataflow-time-avg] 17 16]
  [:value [:pedestal :debug :dataflow-time] 18 8]
  :break
  [:value [:tutorial :my-counter] 2 3]
  [:value [:tutorial :average-count] 3 3.33]
  [:value [:tutorial :total-count] 9 10]
  :break
  [:value [:tutorial :my-counter] 3 4]
  [:value [:tutorial :average-count] 3.33 3.67]
  [:value [:tutorial :total-count] 10 11]
  [:value [:pedestal :debug :dataflow-time-avg] 16 15]
  [:value [:pedestal :debug :dataflow-time] 8 10]
  :break
  [:value [:tutorial :other-counters "xyz"] 2 3]
  [:value [:tutorial :average-count] 3.67 4]
  [:value [:tutorial :total-count] 11 12]
  [:value [:pedestal :debug :dataflow-time] 10 14]
  :break
  [:value [:tutorial :other-counters "abc"] 5 6]
  [:value [:tutorial :average-count] 4 4.33]
  [:value [:tutorial :max-count] 5 6]
  [:value [:tutorial :total-count] 12 13]
  [:value [:pedestal :debug :dataflow-time] 14 11]
  :break
  [:value [:tutorial :my-counter] 4 5]
  [:value [:tutorial :average-count] 4.33 4.67]
  [:value [:tutorial :total-count] 13 14]
  [:value [:pedestal :debug :dataflow-time-avg] 15 14]
  [:value [:pedestal :debug :dataflow-time] 11 9]
  :break
  [:value [:tutorial :my-counter] 5 6]
  [:value [:tutorial :average-count] 4.67 5]
  [:value [:tutorial :total-count] 14 15]
  :break
  [:value [:tutorial :my-counter] 6 7]
  [:value [:tutorial :average-count] 5 5.33]
  [:value [:tutorial :max-count] 6 7]
  [:value [:tutorial :total-count] 15 16]
  :break
  [:value [:tutorial :my-counter] 7 8]
  [:value [:tutorial :average-count] 5.33 5.67]
  [:value [:tutorial :max-count] 7 8]
  [:value [:tutorial :total-count] 16 17]
  :break
  [:value [:tutorial :my-counter] 8 9]
  [:value [:tutorial :average-count] 5.67 6]
  [:value [:tutorial :max-count] 8 9]
  [:value [:tutorial :total-count] 17 18]
  [:value [:pedestal :debug :dataflow-time] 9 10]
  :break
  [:value [:tutorial :my-counter] 9 10]
  [:value [:tutorial :average-count] 6 6.33]
  [:value [:tutorial :max-count] 9 10]
  [:value [:tutorial :total-count] 18 19]
  [:value [:pedestal :debug :dataflow-time-avg] 14 13]
  [:value [:pedestal :debug :dataflow-time] 10 9]
  :break
  [:value [:tutorial :other-counters "abc"] 6 7]
  [:value [:tutorial :average-count] 6.33 6.67]
  [:value [:tutorial :total-count] 19 20]
  [:value [:pedestal :debug :dataflow-time] 9 8]
  :break
  [:value [:tutorial :my-counter] 10 11]
  [:value [:tutorial :average-count] 6.67 7]
  [:value [:tutorial :max-count] 10 11]
  [:value [:tutorial :total-count] 20 21]
  [:value [:pedestal :debug :dataflow-time] 8 10]
  :break
  [:value [:tutorial :my-counter] 11 12]
  [:value [:tutorial :average-count] 7 7.33]
  [:value [:tutorial :max-count] 11 12]
  [:value [:tutorial :total-count] 21 22]
  :break
  [:value [:tutorial :other-counters "abc"] 7 8]
  [:value [:tutorial :average-count] 7.33 7.67]
  [:value [:tutorial :total-count] 22 23]
  [:value [:pedestal :debug :dataflow-time] 10 9]
  :break
  [:value [:tutorial :my-counter] 12 13]
  [:value [:tutorial :average-count] 7.67 8]
  [:value [:tutorial :max-count] 12 13]
  [:value [:tutorial :total-count] 23 24]
  :break
  [:value [:tutorial :other-counters "xyz"] 3 4]
  [:value [:tutorial :average-count] 8 8.33]
  [:value [:tutorial :total-count] 24 25]
  [:value [:pedestal :debug :dataflow-time-avg] 13 12]
  [:value [:pedestal :debug :dataflow-time] 9 8]
  :break
  [:value [:tutorial :my-counter] 13 14]
  [:value [:tutorial :average-count] 8.33 8.67]
  [:value [:tutorial :max-count] 13 14]
  [:value [:tutorial :total-count] 25 26]
  [:value [:pedestal :debug :dataflow-time] 8 10]
  :break
  [:value [:tutorial :my-counter] 14 15]
  [:value [:tutorial :average-count] 8.67 9]
  [:value [:tutorial :max-count] 14 15]
  [:value [:tutorial :total-count] 26 27]
  [:value [:pedestal :debug :dataflow-time] 10 12]
  :break
  [:value [:tutorial :my-counter] 15 16]
  [:value [:tutorial :average-count] 9 9.33]
  [:value [:tutorial :max-count] 15 16]
  [:value [:tutorial :total-count] 27 28]
  [:value [:pedestal :debug :dataflow-time] 12 11]
  :break
  [:value [:tutorial :my-counter] 16 17]
  [:value [:tutorial :average-count] 9.33 9.67]
  [:value [:tutorial :max-count] 16 17]
  [:value [:tutorial :total-count] 28 29]
  [:value [:pedestal :debug :dataflow-time] 11 9]
  :break
  [:value [:tutorial :my-counter] 17 18]
  [:value [:tutorial :average-count] 9.67 10]
  [:value [:tutorial :max-count] 17 18]
  [:value [:tutorial :total-count] 29 30]
  [:value [:pedestal :debug :dataflow-time] 9 8]
  :break
  [:value [:tutorial :my-counter] 18 19]
  [:value [:tutorial :average-count] 10 10.33]
  [:value [:tutorial :max-count] 18 19]
  [:value [:tutorial :total-count] 30 31]
  [:value [:pedestal :debug :dataflow-time] 8 11]
  :break
  [:value [:tutorial :other-counters "abc"] 8 9]
  [:value [:tutorial :average-count] 10.33 10.67]
  [:value [:tutorial :total-count] 31 32]
  [:value [:pedestal :debug :dataflow-time-avg] 12 11]
  [:value [:pedestal :debug :dataflow-time] 11 8]
  :break
  [:value [:tutorial :my-counter] 19 20]
  [:value [:tutorial :average-count] 10.67 11]
  [:value [:tutorial :max-count] 19 20]
  [:value [:tutorial :total-count] 32 33]
  :break
  [:value [:tutorial :my-counter] 20 21]
  [:value [:tutorial :average-count] 11 11.33]
  [:value [:tutorial :max-count] 20 21]
  [:value [:tutorial :total-count] 33 34]
  [:value [:pedestal :debug :dataflow-time] 8 9]
  :break
  [:value [:tutorial :my-counter] 21 22]
  [:value [:tutorial :average-count] 11.33 11.67]
  [:value [:tutorial :max-count] 21 22]
  [:value [:tutorial :total-count] 34 35]
  [:value [:pedestal :debug :dataflow-time] 9 8]
  :break
  [:value [:tutorial :my-counter] 22 23]
  [:value [:tutorial :average-count] 11.67 12]
  [:value [:tutorial :max-count] 22 23]
  [:value [:tutorial :total-count] 35 36]
  [:value [:pedestal :debug :dataflow-time] 8 20]
  :break
  [:value [:tutorial :my-counter] 23 24]
  [:value [:tutorial :average-count] 12 12.33]
  [:value [:tutorial :max-count] 23 24]
  [:value [:tutorial :total-count] 36 37]
  [:value [:pedestal :debug :dataflow-time] 20 11]
  :break
  [:value [:tutorial :my-counter] 24 25]
  [:value [:tutorial :average-count] 12.33 12.67]
  [:value [:tutorial :max-count] 24 25]
  [:value [:tutorial :total-count] 37 38]
  [:value [:pedestal :debug :dataflow-time] 11 8]
  :break
  [:value [:tutorial :my-counter] 25 26]
  [:value [:tutorial :average-count] 12.67 13]
  [:value [:tutorial :max-count] 25 26]
  [:value [:tutorial :total-count] 38 39]
  [:value [:pedestal :debug :dataflow-time] 8 9]
  :break
  [:value [:tutorial :my-counter] 26 27]
  [:value [:tutorial :average-count] 13 13.33]
  [:value [:tutorial :max-count] 26 27]
  [:value [:tutorial :total-count] 39 40]
  :break
  [:value [:tutorial :my-counter] 27 28]
  [:value [:tutorial :average-count] 13.33 13.67]
  [:value [:tutorial :max-count] 27 28]
  [:value [:tutorial :total-count] 40 41]
  [:value [:pedestal :debug :dataflow-time] 9 7]
  :break
  [:value [:tutorial :my-counter] 28 29]
  [:value [:tutorial :average-count] 13.67 14]
  [:value [:tutorial :max-count] 28 29]
  [:value [:tutorial :total-count] 41 42]
  [:value [:pedestal :debug :dataflow-time] 7 8]
  :break
  [:value [:tutorial :my-counter] 29 30]
  [:value [:tutorial :average-count] 14 14.33]
  [:value [:tutorial :max-count] 29 30]
  [:value [:tutorial :total-count] 42 43]
  [:value [:pedestal :debug :dataflow-time] 8 9]
  :break
  [:value [:tutorial :other-counters "abc"] 9 10]
  [:value [:tutorial :average-count] 14.33 14.67]
  [:value [:tutorial :total-count] 43 44]
  [:value [:pedestal :debug :dataflow-time] 9 15]
  :break
  [:value [:tutorial :other-counters "xyz"] 4 5]
  [:value [:tutorial :average-count] 14.67 15]
  [:value [:tutorial :total-count] 44 45]
  [:value [:pedestal :debug :dataflow-time] 15 9]
  :break
  [:value [:tutorial :other-counters "abc"] 10 11]
  [:value [:tutorial :average-count] 15 15.33]
  [:value [:tutorial :total-count] 45 46]
  [:value [:pedestal :debug :dataflow-time] 9 13]
  :break
  [:value [:tutorial :other-counters "abc"] 11 12]
  [:value [:tutorial :average-count] 15.33 15.67]
  [:value [:tutorial :total-count] 46 47]
  [:value [:pedestal :debug :dataflow-time] 13 19]
  :break
  [:value [:tutorial :other-counters "abc"] 12 13]
  [:value [:tutorial :average-count] 15.67 16]
  [:value [:tutorial :total-count] 47 48]
  :break
  [:value [:tutorial :other-counters "xyz"] 5 6]
  [:value [:tutorial :average-count] 16 16.33]
  [:value [:tutorial :total-count] 48 49]
  [:value [:pedestal :debug :dataflow-time] 19 20]
  :break
  [:value [:tutorial :other-counters "abc"] 13 14]
  [:value [:tutorial :average-count] 16.33 16.67]
  [:value [:tutorial :total-count] 49 50]
  [:value [:pedestal :debug :dataflow-time] 20 9]
  :break
  [:value [:tutorial :other-counters "abc"] 14 15]
  [:value [:tutorial :average-count] 16.67 17]
  [:value [:tutorial :total-count] 50 51]
  [:value [:pedestal :debug :dataflow-time-avg] 11 12]
  [:value [:pedestal :debug :dataflow-time] 9 26]
  :break
  [:value [:tutorial :other-counters "xyz"] 6 7]
  [:value [:tutorial :average-count] 17 17.33]
  [:value [:tutorial :total-count] 51 52]
  [:value [:pedestal :debug :dataflow-time] 26 9]
 ]}
