{:config {:name :tutorial, :description "Tutorial", :order 0}
 :data
 [
  [:node-create [] :map]
  [:node-create [:main] :map]
  [:node-create [:main :my-counter] :map]
  [:value [:main :my-counter] nil 1]
  [:transform-enable [:main :my-counter] :inc [{:io.pedestal.app.messages/topic [:my-counter]}]]
  [:node-create [:main :other-counters] :map]
  [:node-create [:main :other-counters "abc"] :map]
  [:value [:main :other-counters "abc"] nil 2]
  [:node-create [:main :other-counters "xyz"] :map]
  [:value [:main :other-counters "xyz"] nil 1]
  [:node-create [:main :total-count] :map]
  [:value [:main :total-count] nil 4]
  [:node-create [:main :average-count] :map]
  [:value [:main :average-count] nil 2]
  [:node-create [:main :max-count] :map]
  [:value [:main :max-count] nil 2]
  [:node-create [:pedestal] :map]
  [:node-create [:pedestal :debug] :map]
  [:node-create [:pedestal :debug :dataflow-time-avg] :map]
  [:value [:pedestal :debug :dataflow-time-avg] nil 20]
  [:node-create [:pedestal :debug :dataflow-time-max] :map]
  [:value [:pedestal :debug :dataflow-time-max] nil 30]
  [:node-create [:pedestal :debug :dataflow-time] :map]
  [:value [:pedestal :debug :dataflow-time] nil 16]
  :break
  [:value [:main :other-counters "abc"] 2 3]
  [:value [:main :average-count] 2 2.5]
  [:value [:main :max-count] 2 3]
  [:value [:main :total-count] 4 5]
  [:value [:pedestal :debug :dataflow-time-avg] 20 19]
  [:value [:pedestal :debug :dataflow-time] 16 13]
  :break
  [:value [:main :other-counters "xyz"] 1 2]
  [:value [:main :average-count] 2.5 2]
  [:value [:main :total-count] 5 6]
  :break
  [:value [:main :my-counter] 1 2]
  [:value [:main :average-count] 2 3.5]
  [:value [:main :total-count] 6 7]
  [:value [:pedestal :debug :dataflow-time-avg] 19 17]
  [:value [:pedestal :debug :dataflow-time] 13 12]
  :break
  [:value [:main :other-counters "abc"] 3 4]
  [:value [:main :average-count] 3.5 4]
  [:value [:main :max-count] 3 4]
  [:value [:main :total-count] 7 8]
  :break
  [:value [:main :my-counter] 2 3]
  [:value [:main :average-count] 4 3]
  [:value [:main :total-count] 8 9]
  [:value [:pedestal :debug :dataflow-time] 12 13]
  :break
  [:value [:main :my-counter] 3 4]
  [:value [:main :average-count] 3 5]
  [:value [:main :total-count] 9 10]
  [:value [:pedestal :debug :dataflow-time-avg] 17 16]
  [:value [:pedestal :debug :dataflow-time] 13 11]
  :break
  [:value [:main :my-counter] 4 5]
  [:value [:main :average-count] 5 3.67]
  [:value [:main :max-count] 4 5]
  [:value [:main :total-count] 10 11]
  [:value [:pedestal :debug :dataflow-time-avg] 16 15]
  [:value [:pedestal :debug :dataflow-time] 11 12]
  :break
  [:value [:main :my-counter] 5 6]
  [:value [:main :average-count] 3.67 4]
  [:value [:main :max-count] 5 6]
  [:value [:main :total-count] 11 12]
  [:value [:pedestal :debug :dataflow-time] 12 11]
  :break
  [:value [:main :my-counter] 6 7]
  [:value [:main :average-count] 4 4.33]
  [:value [:main :max-count] 6 7]
  [:value [:main :total-count] 12 13]
  :break
  [:value [:main :my-counter] 7 8]
  [:value [:main :average-count] 4.33 4.67]
  [:value [:main :max-count] 7 8]
  [:value [:main :total-count] 13 14]
  [:value [:pedestal :debug :dataflow-time] 11 15]
  :break
  [:value [:main :my-counter] 8 9]
  [:value [:main :average-count] 4.67 5]
  [:value [:main :max-count] 8 9]
  [:value [:main :total-count] 14 15]
  [:value [:pedestal :debug :dataflow-time] 15 13]
  :break
  [:value [:main :my-counter] 9 10]
  [:value [:main :average-count] 5 5.33]
  [:value [:main :max-count] 9 10]
  [:value [:main :total-count] 15 16]
  [:value [:pedestal :debug :dataflow-time-avg] 15 14]
  [:value [:pedestal :debug :dataflow-time] 13 10]
  :break
  [:value [:main :my-counter] 10 11]
  [:value [:main :average-count] 5.33 5.67]
  [:value [:main :max-count] 10 11]
  [:value [:main :total-count] 16 17]
  [:value [:pedestal :debug :dataflow-time] 10 13]
  :break
  [:value [:main :my-counter] 11 12]
  [:value [:main :average-count] 5.67 6]
  [:value [:main :max-count] 11 12]
  [:value [:main :total-count] 17 18]
  :break
  [:value [:main :other-counters "abc"] 4 5]
  [:value [:main :average-count] 6 6.33]
  [:value [:main :total-count] 18 19]
  :break
  [:value [:main :my-counter] 12 13]
  [:value [:main :average-count] 6.33 6.67]
  [:value [:main :max-count] 12 13]
  [:value [:main :total-count] 19 20]
  [:value [:pedestal :debug :dataflow-time] 13 11]
  :break
  [:value [:main :my-counter] 13 14]
  [:value [:main :average-count] 6.67 7]
  [:value [:main :max-count] 13 14]
  [:value [:main :total-count] 20 21]
  [:value [:pedestal :debug :dataflow-time] 11 12]
  :break
  [:value [:main :my-counter] 14 15]
  [:value [:main :average-count] 7 7.33]
  [:value [:main :max-count] 14 15]
  [:value [:main :total-count] 21 22]
  :break
  [:value [:main :my-counter] 15 16]
  [:value [:main :average-count] 7.33 7.67]
  [:value [:main :max-count] 15 16]
  [:value [:main :total-count] 22 23]
  [:value [:pedestal :debug :dataflow-time] 12 13]
  :break
  [:value [:main :my-counter] 16 17]
  [:value [:main :average-count] 7.67 8]
  [:value [:main :max-count] 16 17]
  [:value [:main :total-count] 23 24]
  [:value [:pedestal :debug :dataflow-time] 13 17]
  :break
  [:value [:main :my-counter] 17 18]
  [:value [:main :average-count] 8 8.33]
  [:value [:main :max-count] 17 18]
  [:value [:main :total-count] 24 25]
  [:value [:pedestal :debug :dataflow-time-avg] 14 15]
  [:value [:pedestal :debug :dataflow-time-max] 30 32]
  [:value [:pedestal :debug :dataflow-time] 17 32]
  :break
  [:value [:main :my-counter] 18 19]
  [:value [:main :average-count] 8.33 8.67]
  [:value [:main :max-count] 18 19]
  [:value [:main :total-count] 25 26]
  [:value [:pedestal :debug :dataflow-time] 32 13]
  :break
  [:value [:main :my-counter] 19 20]
  [:value [:main :average-count] 8.67 9]
  [:value [:main :max-count] 19 20]
  [:value [:main :total-count] 26 27]
  [:value [:pedestal :debug :dataflow-time-avg] 15 14]
  [:value [:pedestal :debug :dataflow-time] 13 12]
  :break
  [:value [:main :my-counter] 20 21]
  [:value [:main :average-count] 9 9.33]
  [:value [:main :max-count] 20 21]
  [:value [:main :total-count] 27 28]
  :break
  [:value [:main :my-counter] 21 22]
  [:value [:main :average-count] 9.33 9.67]
  [:value [:main :max-count] 21 22]
  [:value [:main :total-count] 28 29]
  [:value [:pedestal :debug :dataflow-time] 12 11]
  :break
  [:value [:main :my-counter] 22 23]
  [:value [:main :average-count] 9.67 10]
  [:value [:main :max-count] 22 23]
  [:value [:main :total-count] 29 30]
  [:value [:pedestal :debug :dataflow-time] 11 12]
  :break
  [:value [:main :other-counters "xyz"] 2 3]
  [:value [:main :average-count] 10 10.33]
  [:value [:main :total-count] 30 31]
  [:value [:pedestal :debug :dataflow-time-avg] 14 15]
  [:value [:pedestal :debug :dataflow-time] 12 26]
  :break
  [:value [:main :my-counter] 23 24]
  [:value [:main :average-count] 10.33 10.67]
  [:value [:main :max-count] 23 24]
  [:value [:main :total-count] 31 32]
  [:value [:pedestal :debug :dataflow-time] 26 14]
  :break
  [:value [:main :other-counters "abc"] 5 6]
  [:value [:main :average-count] 10.67 11]
  [:value [:main :total-count] 32 33]
  [:value [:pedestal :debug :dataflow-time-avg] 15 14]
  [:value [:pedestal :debug :dataflow-time] 14 11]
  :break
  [:value [:main :my-counter] 24 25]
  [:value [:main :average-count] 11 11.33]
  [:value [:main :max-count] 24 25]
  [:value [:main :total-count] 33 34]
  [:value [:pedestal :debug :dataflow-time] 11 12]
  :break
  [:value [:main :my-counter] 25 26]
  [:value [:main :average-count] 11.33 11.67]
  [:value [:main :max-count] 25 26]
  [:value [:main :total-count] 34 35]
  [:value [:pedestal :debug :dataflow-time] 12 11]
  :break
  [:value [:main :my-counter] 26 27]
  [:value [:main :average-count] 11.67 12]
  [:value [:main :max-count] 26 27]
  [:value [:main :total-count] 35 36]
  [:value [:pedestal :debug :dataflow-time] 11 12]
 ]}