{:config {:name :tutorial, :description "Tutorial Recording", :order 0}
 :data
 [
  [:node-create [] :map]
  [:node-create [:main] :map]
  [:node-create [:main :my-counter] :map]
  [:value [:main :my-counter] nil 1]
  [:transform-enable [:main :my-counter] :inc [{:io.pedestal.app.messages/topic [:my-counter]}]]
  [:node-create [:main :average-count] :map]
  [:value [:main :average-count] nil 4]
  [:node-create [:main :max-count] :map]
  [:value [:main :max-count] nil 8]
  [:node-create [:main :total-count] :map]
  [:value [:main :total-count] nil 12]
  [:node-create [:main :other-counters] :map]
  [:node-create [:main :other-counters "abc"] :map]
  [:value [:main :other-counters "abc"] nil 8]
  [:node-create [:main :other-counters "xyz"] :map]
  [:value [:main :other-counters "xyz"] nil 3]
  [:node-create [:pedestal] :map]
  [:node-create [:pedestal :debug] :map]
  [:node-create [:pedestal :debug :dataflow-time-avg] :map]
  [:value [:pedestal :debug :dataflow-time-avg] nil 17]
  [:node-create [:pedestal :debug :dataflow-time-max] :map]
  [:value [:pedestal :debug :dataflow-time-max] nil 24]
  [:node-create [:pedestal :debug :dataflow-time] :map]
  [:value [:pedestal :debug :dataflow-time] nil 16]
  :break
  [:value [:main :other-counters "xyz"] 3 4]
  [:value [:main :average-count] 4 4.33]
  [:value [:main :total-count] 12 13]
  [:value [:pedestal :debug :dataflow-time-avg] 17 16]
  [:value [:pedestal :debug :dataflow-time] 16 10]
  :break
  [:value [:main :other-counters "abc"] 8 9]
  [:value [:main :average-count] 4.33 4.67]
  [:value [:main :max-count] 8 9]
  [:value [:main :total-count] 13 14]
  [:value [:pedestal :debug :dataflow-time] 10 12]
  :break
  [:value [:main :my-counter] 1 2]
  [:value [:main :average-count] 4.67 5]
  [:value [:main :total-count] 14 15]
  [:value [:pedestal :debug :dataflow-time-avg] 16 15]
  [:value [:pedestal :debug :dataflow-time] 12 11]
  :break
  [:value [:main :my-counter] 2 3]
  [:value [:main :average-count] 5 5.33]
  [:value [:main :total-count] 15 16]
  [:value [:pedestal :debug :dataflow-time] 11 10]
  :break
  [:value [:main :my-counter] 3 4]
  [:value [:main :average-count] 5.33 8.5]
  [:value [:main :total-count] 16 17]
  [:value [:pedestal :debug :dataflow-time] 10 12]
  :break
  [:value [:main :my-counter] 4 5]
  [:value [:main :average-count] 8.5 6]
  [:value [:main :total-count] 17 18]
  [:value [:pedestal :debug :dataflow-time-avg] 15 14]
  [:value [:pedestal :debug :dataflow-time] 12 11]
  :break
  [:value [:main :my-counter] 5 6]
  [:value [:main :average-count] 6 6.33]
  [:value [:main :total-count] 18 19]
  [:value [:pedestal :debug :dataflow-time] 11 10]
  :break
  [:value [:main :my-counter] 6 7]
  [:value [:main :average-count] 6.33 6.67]
  [:value [:main :total-count] 19 20]
  :break
  [:value [:main :my-counter] 7 8]
  [:value [:main :average-count] 6.67 7]
  [:value [:main :total-count] 20 21]
  :break
  [:value [:main :my-counter] 8 9]
  [:value [:main :average-count] 7 11]
  [:value [:main :total-count] 21 22]
  :break
  [:value [:main :my-counter] 9 10]
  [:value [:main :average-count] 11 7.67]
  [:value [:main :max-count] 9 10]
  [:value [:main :total-count] 22 23]
  [:value [:pedestal :debug :dataflow-time] 10 12]
  :break
  [:value [:main :my-counter] 10 11]
  [:value [:main :average-count] 7.67 8]
  [:value [:main :max-count] 10 11]
  [:value [:main :total-count] 23 24]
  :break
  [:value [:main :other-counters "abc"] 9 10]
  [:value [:main :average-count] 8 8.33]
  [:value [:main :total-count] 24 25]
  [:value [:pedestal :debug :dataflow-time] 12 11]
  :break
  [:value [:main :my-counter] 11 12]
  [:value [:main :average-count] 8.33 8.67]
  [:value [:main :max-count] 11 12]
  [:value [:main :total-count] 25 26]
  [:value [:pedestal :debug :dataflow-time] 11 14]
 ]}