{:config {:name :wait, :description "Wait", :order 0}
 :data
 [
  [:node-create [] :map]
  [:node-create [:login] :map]
  [:node-create [:login :name] :map]
  [:transform-enable [:login :name] :login [{:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:login :name], :io.pedestal.app.messages.param/value {}} {:io.pedestal.app.messages/type :set-focus, :io.pedestal.app.messages/topic :io.pedestal.app.messages/app-model, :name :wait}]]
  :break
  [:value [:login :name] nil "Feanor"]
  :break
  [:value [:login :name] "Feanor" nil]
  [:transform-disable [:login :name] :login [{:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:login :name], :io.pedestal.app.messages.param/value {}} {:io.pedestal.app.messages/type :set-focus, :io.pedestal.app.messages/topic :io.pedestal.app.messages/app-model, :name :wait}]]
  [:node-destroy [:login :name] :map]
  [:node-destroy [:login] :map]
  [:node-create [:wait] :map]
  [:node-create [:wait :start] :map]
  [:transform-enable [:wait :start] :start-game [{:io.pedestal.app.messages/topic :io.pedestal.app.messages/output, :payload {:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:active-game], :value true}} {:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:active-game], :value true}]]
  [:node-create [:wait :counters] :map]
  [:node-create [:wait :counters "Feanor"] :map]
  :break
  [:node-create [:wait :counters "abc"] :map]
  [:value [:wait :counters "abc"] nil 0]
  :break
  [:value [:wait :counters "abc"] 0 1]
  :break
  [:node-create [:wait :counters "xyz"] :map]
  [:value [:wait :counters "xyz"] nil 1]
  :break
  [:value [:wait :counters "abc"] 1 nil]
  [:node-destroy [:wait :counters "abc"] :map]
  [:value [:wait :counters "xyz"] 1 nil]
  [:node-destroy [:wait :counters "xyz"] :map]
  [:node-destroy [:wait :counters "Feanor"] :map]
  [:node-destroy [:wait :counters] :map]
  [:transform-disable [:wait :start] :start-game [{:io.pedestal.app.messages/topic :io.pedestal.app.messages/output, :payload {:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:active-game], :value true}} {:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:active-game], :value true}]]
  [:node-destroy [:wait :start] :map]
  [:node-destroy [:wait] :map]
  [:node-create [:main] :map]
  [:node-create [:main :my-counter] :map]
  [:transform-enable [:main :my-counter] :add-points [{:io.pedestal.app.messages/topic [:my-counter], :io.pedestal.app.messages.param/points {}}]]
  [:node-create [:main :average-count] :map]
  [:value [:main :average-count] nil 1]
  [:node-create [:main :max-count] :map]
  [:value [:main :max-count] nil 1]
  [:node-create [:main :total-count] :map]
  [:value [:main :total-count] nil 2]
  [:node-create [:main :counters] :map]
  [:node-create [:main :counters "Feanor"] :map]
  [:node-create [:main :counters "xyz"] :map]
  [:value [:main :counters "xyz"] nil 1]
  [:node-create [:main :counters "abc"] :map]
  [:value [:main :counters "abc"] nil 1]
  [:node-create [:pedestal] :map]
  [:node-create [:pedestal :debug] :map]
  [:node-create [:pedestal :debug :dataflow-time-avg] :map]
  [:value [:pedestal :debug :dataflow-time-avg] nil 17]
  [:node-create [:pedestal :debug :dataflow-time-max] :map]
  [:value [:pedestal :debug :dataflow-time-max] nil 37]
  [:node-create [:pedestal :debug :dataflow-time] :map]
  [:value [:pedestal :debug :dataflow-time] nil 31]
  [:node-create [:main :player-order] :map]
  [:node-create [:main :player-order "abc"] :map]
  [:value [:main :player-order "abc"] nil 1]
  [:node-create [:main :player-order "xyz"] :map]
  [:value [:main :player-order "xyz"] nil 0]
  [:node-create [:main :player-order "Feanor"] :map]
  [:value [:main :player-order "Feanor"] nil 2]
  [:node-create [:main :remove-bubbles] :map]
  [:value [:main :remove-bubbles] nil {:total 2}]
  [:node-create [:main :add-bubbles] :map]
  [:value [:main :add-bubbles] nil {:clock 7, :count 3}]
  :break
  [:value [:main :add-bubbles] {:clock 7, :count 3} {:clock 8, :count 3}]
  [:value [:pedestal :debug :dataflow-time] 31 13]
  :break
  [:value [:main :average-count] 1 0.33]
  [:value [:main :total-count] 2 1]
  [:value [:main :counters "xyz"] 1 0]
  [:value [:main :player-order "abc"] 1 0]
  [:value [:main :player-order "xyz"] 0 1]
  [:value [:main :remove-bubbles] {:total 2} {:total 1}]
  [:value [:pedestal :debug :dataflow-time-avg] 17 18]
  [:value [:pedestal :debug :dataflow-time] 13 32]
  :break
  [:value [:main :average-count] 0.33 0.67]
  [:value [:main :max-count] 1 2]
  [:value [:main :total-count] 1 2]
  [:value [:main :counters "abc"] 1 2]
  [:value [:main :remove-bubbles] {:total 1} {:total 2}]
  [:value [:pedestal :debug :dataflow-time] 32 29]
  :break
  [:value [:main :add-bubbles] {:clock 8, :count 3} {:clock 9, :count 3}]
  [:value [:pedestal :debug :dataflow-time] 29 8]
  :break
  [:value [:main :average-count] 0.67 1]
  [:value [:main :max-count] 2 3]
  [:value [:main :total-count] 2 3]
  [:value [:main :counters "abc"] 2 3]
  [:value [:main :remove-bubbles] {:total 2} {:total 3}]
  [:value [:pedestal :debug :dataflow-time] 8 22]
  :break
  [:value [:main :add-bubbles] {:clock 9, :count 3} {:clock 10, :count 3}]
  [:value [:pedestal :debug :dataflow-time] 22 16]
  :break
  [:value [:main :average-count] 1 1.67]
  [:value [:main :total-count] 3 5]
  [:value [:main :counters "xyz"] 0 2]
  [:value [:main :remove-bubbles] {:total 3} {:total 5}]
  [:value [:pedestal :debug :dataflow-time] 16 29]
  :break
  [:value [:main :average-count] 1.67 2]
  [:value [:main :max-count] 3 4]
  [:value [:main :total-count] 5 6]
  [:value [:main :counters "abc"] 3 4]
  [:value [:main :remove-bubbles] {:total 5} {:total 6}]
  [:value [:pedestal :debug :dataflow-time-avg] 18 19]
  [:value [:pedestal :debug :dataflow-time] 29 21]
  :break
  [:value [:main :average-count] 2 68.67]
  [:value [:main :max-count] 4 200]
  [:value [:main :total-count] 6 206]
  [:value [:main :counters "Feanor"] nil 200]
  [:value [:main :player-order "abc"] 0 1]
  [:value [:main :player-order "xyz"] 1 2]
  [:value [:main :player-order "Feanor"] 2 0]
  [:value [:pedestal :debug :dataflow-time] 21 25]
  :break
  [:value [:main :add-bubbles] {:clock 10, :count 3} {:clock 11, :count 3}]
  [:value [:pedestal :debug :dataflow-time-avg] 19 18]
  [:value [:pedestal :debug :dataflow-time] 25 8]
  :break
  [:value [:main :average-count] 68.67 69]
  [:value [:main :total-count] 206 207]
  [:value [:main :counters "abc"] 4 5]
  [:value [:main :remove-bubbles] {:total 6} {:total 7}]
  [:value [:pedestal :debug :dataflow-time] 8 23]
  :break
  [:value [:main :add-bubbles] {:clock 11, :count 3} {:clock 12, :count 3}]
  [:value [:pedestal :debug :dataflow-time] 23 6]
  :break
  [:value [:main :average-count] 69 69.33]
  [:value [:main :total-count] 207 208]
  [:value [:main :counters "xyz"] 2 3]
  [:value [:main :remove-bubbles] {:total 7} {:total 8}]
  [:value [:pedestal :debug :dataflow-time] 6 18]
  :break
  [:value [:main :average-count] 69.33 69.67]
  [:value [:main :total-count] 208 209]
  [:value [:main :counters "abc"] 5 6]
  [:value [:main :remove-bubbles] {:total 8} {:total 9}]
  [:value [:pedestal :debug :dataflow-time] 18 21]
  :break
  [:value [:main :add-bubbles] {:clock 12, :count 3} {:clock 13, :count 3}]
  [:value [:pedestal :debug :dataflow-time] 21 10]
 ]}